---
- name: Software installation
  hosts: servergroup
  tasks:
      - name: install nginx
        apt: name=nginx state=latest
      - name: start nginx service
        service:
            name: nginx
            state: started